//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public string modelo { get; set; }
        public string tipo { get; set; }
        public int cantpasajeros { get; set; }
        public string ubicacion { get; set; }
        public string servicios { get; set; }
        public string extras { get; set; }
        public string restricciones { get; set; }
        public string transmision { get; set; }
        public int kilometraje { get; set; }
        public string empresa { get; set; }
        public double precioxdia { get; set; }
        public string imagen { get; set; }
    }
}
