//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int Id { get; set; }
        public string vuelo { get; set; }
        public string aerolinea { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public string fecha { get; set; }
        public string horasalida { get; set; }
        public string horallegada { get; set; }
        public string duracion { get; set; }
        public string serviciosincluidos { get; set; }
        public Nullable<int> disponibles { get; set; }
        public string avion { get; set; }
    }
}
