//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightReservation
    {
        public int Id { get; set; }
        public int idVuelo { get; set; }
        public int idCliente { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public Nullable<int> cantpasajeros { get; set; }
        public string asientos { get; set; }
        public string clase { get; set; }
        public Nullable<double> costototal { get; set; }
    }
}
